version: 2

before:
  hooks:
    - go mod tidy

project_name: renovate-controller

builds:
  - id: controller-webhook
    main: ./cmd/controller-webhook/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - '-s -w'

  - id: controller
    main: ./cmd/controller/main.go
    binary: controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - '-s -w'

archives:
  - id: lambda_archive
    builds:
      - controller-webhook
    files:
      - ./dist/controller-webhook_{{ .Os }}_{{ .Arch }}*/bootstrap
    name_template: "{{ .ProjectName }}-webhook-{{ .Os }}-{{ .Arch }}"
    formats: ['zip']

  - id: server_archive
    builds:
      - controller
    files:
      - ./dist/controller_{{ .Os }}_{{ .Arch }}*/controller
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats: ['zip']

release:
  draft: true

changelog:
  disable: true
